<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot_name">
    <xacro:include filename="$(find docbot_description)/urdf/properties.xacro"/>
    <link name="imu_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
        </visual>
        <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
                <box size="0.01 0.01 0.01"/>
        </geometry>
    </collision>
    <xacro:inertial_box mass="0.1" x="0.01" y="0.01" z="0.01">
            <origin xyz="0 0 ${base_height}+${wheel_radius*2}-${wheel_zoff}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="mpu_joint" type="fixed">
        <origin xyz="0.0 0.0 ${base_height}+${wheel_radius*2}-${wheel_zoff}"/>
        <parent link="base_link"/>
        <child link="imu_link"/>
        <axis xyz="0 0 0" />
    </joint>
</robot>